Generate Rust types for types used in BPF maps
libbpf/libbpf-rs pull request #809
Opened 2024-06-20 21:27 UTC by danielocfb

Generate Rust correspondents for the types used in BPF maps. Having these types generated will eliminate the need for miscellaneous hacks to be employed to get the corresponding Rust types by other means.

Closes: #602

2024-06-21 22:23 UTC, anakryiko reviewed
Do you have an example skeleton.rs code generated? I'm failing to see how this all just auto-magically works for key/value types of map?...

2024-06-24 16:33 UTC, danielocfb commented
> Do you have an example skeleton.rs code generated?

I tried it with the `capable` skeleton.
https://gist.github.com/danielocfb/c73a4e12161ce2a888b410f78864fd3c
https://gist.github.com/danielocfb/046d0e8f3529f78a9e718ff462028b5d

2024-06-24 16:54 UTC, anakryiko commented
Ah, ok, so I see that we get a bunch of "garbage types" like `__anon_3`, which then transitively force libbpf-cargo to emit useful types, like `unique_key`. I think it would be best to avoid those anonymous types (which are just a detail on how we capture map definition). 

See https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L1024-L1025, you can directly ask for types that represent key/value of a map (they should be zero if there is no type association).

2024-06-24 22:15 UTC, danielocfb commented
Thanks for the suggestion. Adjusted the code accordingly. Please take another look when you get a chance, @anakryiko.

2024-06-25 04:00 UTC, anakryiko commented on libbpf-cargo/src/test.rs
> +                __type(key, struct unique_key);
as I mentioned above, it's legal to have `__uint(key_size, 8);`, maybe let's add another test for this to make sure this is handled gracefully?

2024-06-25 04:01 UTC, anakryiko requested changes
This looks like a more cleaner approach, let's just make sure to not error out unnecessarily in some corner cases.

2024-06-25 15:37 UTC, danielocfb commented
> This looks like a more cleaner approach, let's just make sure to not error out unnecessarily in some corner cases.

Doesn't really seem necessary. ID 0 is [`void`](https://www.kernel.org/doc/html/next/bpf/btf.html#type-encoding). So it's a terminal type and we just ignore it. There is no error. Anyway, checking `== 0` now.

2024-06-25 17:16 UTC, anakryiko approved these changes
`__type(key, 8);` needs adjustment as discussed offline, but proactively approving as it overall looks good.

2024-06-25 17:26 UTC, merged